# Site settings
title: My blog
header-img: img/home-bg.jpg
email: 1273557346@qq.com
copyright_name: Your/Project/Corporate Name
description: "第一次尝试搭博客写博客"
baseurl: ""
url: "https://yinaoxiong.github.io"
twitter_username: _iblackandwhite
github_username:  YinAoXiong
facebook_username:  尹傲雄
email_username:  1273557346@qq.com

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
# google_tracking_id:

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  use_coderay: true
  hard_wrap: false
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
encoding: UTF-8
