# Site settings
title: 尹傲雄的小站
header-img: img/home-bg.jpg
email: aoxiongyin@qq.com
url: https://blog.yinaoxiong.cn
copyright_name: yinaoxiong's blog All Rights Reserved
#description: "尹傲雄的博客"
twitter_username: _iblackandwhite
github_username:  YinAoXiong
facebook_username:  yinaoxiong
email_username:  aoxiongyin@qq.com

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
google_tracking_id: UA-89678848-1

# Baidu autopush and Baidu Analytics
# To enable baidu autopush and baidu analytics,uncoment below line with true and a baidu tracking ID
open_baiduAutoPush: true
baidu_tracking_id: 0a3215e31b6e078f9c3028fc00baafa3

# The config of comment system gitalk
gitalk_enable: true
gitalk_clientID: 66d905190895554db17b
gitalk_clientSecret: 1e3cb5aa4b5ced7987c7d0e87f9f09ad8bbffc14
gitalk_repo: blog-s-comment
gitalk_owner: YinAoXiong
gitalk_admin: YinAoXiong
# Build settings
markdown: kramdown
kramdown:
  input: GFM
highlighter: rouge
permalink: /:year/:month/:day/:title.html
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
encoding: UTF-8
